import enum

class Label(str, enum.Enum):
    FULL_CREDIT = "FULL_CREDIT"
    PARTIAL_CREDIT = "PARTIAL_CREDIT"
    NO_CREDIT = "NO_CREDIT"
    MISCONCEPTION = "MISCONCEPTION"

class JobStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    EXTRACTING = "EXTRACTING"
    SEGMENTING = "SEGMENTING"
    RETRIEVING = "RETRIEVING"
    EVALUATING = "EVALUATING"
    AUDITING = "AUDITING"
    SCORING = "SCORING"
    ANNOTATING = "ANNOTATING"
    DONE = "DONE"
    FAILED = "FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
